### PR TITLE
adding test case for writing a new document when overwrite=true

### PR DESCRIPTION
**Pull request by jasonpet**
adding a test case for PR #155

### CODE REVIEW

**Comment by jasonpet** [comment]
@rabbah - fyi

**Comment by rabbah** [comment]
hmm why does this test pass already?

**Comment by jasonpet** [comment]
it doesn't for me

**Comment by rabbah** [comment]
fooled by the green checkmark  - i thought that meant travis; sorry wasn't looking closely enough.

**Pull request merged**
